spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    serialization:
      write-dates-as-timestamps: false
    mapper:
      accept-case-insensitive-enums: true
    default-property-inclusion: non_null


# Service Bus
message:
  broker:
    default: servicebus

logging:
  config: classpath:logback-json.xml

feign:
  payment:
    url: http://localhost:8082
